MemberService CRUD 구현입니다.
jungsae/Well-Com pull request #22
Opened 2024-02-15 07:23 UTC by hoonjo123

:: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
[ x] 기능 추가
 리뷰 반영
 리팩토링
 버그 수정
 컨벤션 수정

:: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
멤버리스트조회, 멤버상세조회, 멤버삭제, 멤버수정, 멤버차단 서비스

:: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
멤버상세조회(백앤드)
기본 도메인 외에 sharingroom 횟수, reservation 횟수, desk이용시간 등을 조회할 수 있습니다.

2. 멤버리스트조회(백앤드) - 기본 도메인 외에 총회원수를 조회할 수 있는 기능을 구현하였습니다.
3.멤버삭제
-삭제시 delYn으로 db에 데이터를 남겨두었습니다.

4.멤버수정
5.멤버차단서비스

:: Issue 포인트 ( 해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

:: 기타 질문 및 특이 사항

2024-02-15 08:04 UTC, jungsae commented on src/main/java/com/wellcom/domain/Reservation/Repository/ReservationRepository.java
> +    int countReservationsByMemberId(Long memberId);
여기는 int고 아래는 Integer로 한 이유가 있나요?

2024-02-15 08:13 UTC, jungsae commented on src/main/java/com/wellcom/domain/Member/Controller/MemberController.java
try catch 사용 통일시켜주세요

2024-02-15 08:15 UTC, jungsae commented on src/main/java/com/wellcom/domain/Member/Dto/MemberDetailResDto.java
> +    private Integer totalReservationTime;
Integer 타입이면 초 단위로 저장을 하는건가요?

2024-02-15 08:19 UTC, jungsae commented on src/main/java/com/wellcom/domain/Member/Service/MemberService.java
> +        Member member = memberRepository.findById(id).orElseThrow(()->new EntityNotFoundException("찾을 수 없는 멤버입니다."));
맴버를 찾고 에러 처리를 하는 findById 함수가 있어서, 저 공통 기능으로 이 기능 외에 다른 부분들도 좀 더 간결하게 바꿀 수 있을 거 같습니다.

2024-02-15 08:21 UTC, jungsae requested changes
조금만 수정해주세요

2024-02-15 11:31 UTC, jungsae commented
추가적으로 브랜치, 커밋 컨벤션 확인 후 수정 부탁드립니다.

2024-02-15 11:33 UTC, jungsae reviewed
추가 사항입니다

2024-02-15 11:33 UTC, jungsae commented on src/main/java/com/wellcom/domain/Desk/Controller/DeskController.java
> +    @DeleteMapping("/admin/desk/delete/{deskNum}")
테이블을 완전 삭제가 아니라 delYn으로 수정 표기만 하기 때문에 delete인지 patch인지 고민해봐야합니다

2024-02-16 01:03 UTC, yujeong-shin commented on src/main/java/com/wellcom/domain/Desk/Controller/DeskController.java
> +    @DeleteMapping("/admin/desk/delete/{deskNum}")
이거는 나도 그냥 Delete 매핑으로 두고 컬럼 값만 바꿨는데 같이 고민해봅시다

2024-02-16 05:36 UTC, hoonjo123 commented on src/main/java/com/wellcom/domain/Desk/Controller/DeskController.java
> +    @DeleteMapping("/admin/desk/delete/{deskNum}")
수정사항 반영완료입니다

2024-02-16 05:38 UTC, hoonjo123 commented
수정사항 반영하였습니다.

2024-02-16 06:34 UTC, yujeong-shin commented on src/main/java/com/wellcom/domain/Member/Dto/MemberDetailResDto.java
> +    private Integer totalReservationTime;
Integer를 사용하는 이유를 null값을 가질 수 있어서라고 답변해주셨는데, 총 이용시간은 초기 값이 null이 아니고 0으로 세팅되어야 SUM을 진행할 때 혹시 모를 NullPointer예외라든지... 등등을 예방할 수 있지 않을까요?

2024-02-16 06:35 UTC, yujeong-shin commented
총 이용시간을 Integer 타입으로 두는 것이 바른 설계인지 고민해봅시다.

2024-02-16 07:36 UTC, hoonjo123 commented
1.메인에 올릴때는 환경변수 파일 원본이랑 통일 시켜서 올려주세요.
show sql - true로 통일

2.여기는 int 타입이고 아래는 Integer 타입으로 한 이유가 있나요?

int의 경우 기본데이터타입으로 null값을 가질수 없는반면
integer의 경우 레퍼클래스로 null값을 가질 수 있습니다.

예약 총 시간을 구하는 메소드의 경우, 해당 회원이 아무 예약도 하지 않아 null이 나올 수 있기 때문입니다.
int의 경우, null일 경우 자동으로 0을 반환하게 되는데 예약횟수의 경우 적합하다 판단하여 int로 하였습니다.

3.위의 22번쨰줄에서 사용한 쿼리와 여기서 사용한 쿼리가 거의 동일한 거 같은데, 쿼리를 하나로 통일시키고 서비스에서 처리하는 방법과 지금 사용한 방법중에 어떤게 효율적일까요 (질문임)

분리된 쿼리를 통해 가독성 및 유지보수성을 높이는데 기여하였습니다.

4.try catch 사용 통일시켜주세요 

이미 ExceptionHandlerClass를 통해 예외처리를 중앙화하고 있기 때문에 코드를 좀 더 간결하게 해보겠습니다.

5.Integer 타입이면 초 단위로 저장을 하는건가요?
네 초단위로 계산되고 있습니다.

6.테이블을 완전 삭제가 아니라 delYn으로 수정 표기만 하기 때문에 delete인지 patch인지 고민해봐야합니다
`deleteDesk` 메소드를 수정하고, 공통 응답 형식(`CommonResponse`) 및 중앙화된 예외 처리(`ExceptionHandlerClass`)를 사용하도록 업데이트하였습니다.

7. 총 이용시간을 Integer 타입으로 두는 것이 바른 설계인지 고민해봅시다.

int의 경우 기본데이터타입으로 null값을 가질수 없는반면
integer의 경우 레퍼클래스로 null값을 가질 수 있습니다.

이런 이유로 Integer를 사용하였으나 int로 변경합니다.
변경함에 있어 ReservationRepository 부분의 멤버 총 이용시간 조회하는 쿼리문 coalesce 를 사용하여 수정하였습니다.

8. controller endpoint 수정
9. HttpStatus 상태코드 null이 아닌 각 상태코드에 맞게 변경

2024-02-16 13:42 UTC, jungsae reviewed
수정

2024-02-16 14:06 UTC, closed without merging